### ISSUE TITLE
Do not save remote SQL dump file in typo3temp

### ISSUE THREAD

**Issue by koehnlein** [ochorocho/joro-typo3reversedeployment#11]
If the script will abort, the file keeps accessible via HTTP. Ideas to solve this:

* Use ../ (relative to webroot) to save the dump. You require a composer folder structure to access typo3cms, so it should not be a problem to have write access to this root folder.
* Dynamically create a dedicated folder inside typo3temp and automatically add a .htaccess file to protect files.
* Let user configure the path.

**Comment by ochorocho** [comment]
👍 makes sense. Thanks for your support

**Comment by ochorocho** [comment]
There is now a folder including a .htacces file containig "deny from all". Its created everytime ssh connects.

For NGINX you need to extend the config file, see README.md
