### ISSUE TITLE
Fix path to LocalConfiguration.php

### ISSUE THREAD

**Issue by schliesser** [ochorocho/joro-typo3reversedeployment#15]
https://github.com/ochorocho/joro-typo3reversedeployment/blob/0b65bdb1c36a477f86aa22b8b13398c92d093a0d/JoRo/Typo3ReverseDeployment.php#L401

With the last change on this line, the reverse deployment tool can't fetch the LocalConfiguration.php file.

Error Message:
`PHP Parse error:  syntax error, unexpected 'in' (T_STRING) in /[...]/vendor/joro/typo3reversedeployment/JoRo/Typo3ReverseDeployment.php(404) : eval()'d code on line 1`

The old implementation `$remoteConf = $ssh->exec('cat ' . $path . '/typo3conf/LocalConfiguration.php');` works.

**Comment by ochorocho** [comment]
Thanks for reporting.
I'll fix this as soon as i'm back from holiday.

**Comment by ochorocho** [comment]
Hey, does your LocalConfiguration.php contain 'in' somewhere?

output the config after line 404
```
echo $phpConfig . PHP_EOL;
```

and report the output. Seems like there is an issue with the config file array.

**Comment by ochorocho** [comment]
Closed due to no response. Feel free to reopen it if the problem still exists.
