### ISSUE TITLE
Download of db-dump not working on 1&1 Server

### ISSUE THREAD

**Issue by srosskopf** [ochorocho/joro-typo3reversedeployment#16]
```
Export DB: cd /kunden/homepages/XX/XXXXXXXXX/htdocs/staging/releases/current/html/ && php ../vendor/bin/typo3cms database:export 
rsync: change_dir "/kunden/homepages/XX/XXXXXXXXX/htdocs/staging/releases/current/html/typo3temp/joro_typo3reversedeployment" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(1404) [receiver=2.6.9]
```

When starting the reverser deployment on a 1&1-Server the error message above occurs and no database is being downloaded. Fileadmin works just fine. 

After creating the asked directory `joro_typo3reversedeployment` in `typo3temp` folder, the download of the dump worked.

**Comment by ochorocho** [comment]
Thanks for reporting, i'll make sure this folder is created... Pull requests always welcome ;-)

**Comment by ochorocho** [comment]
Which version do you use?  v1.0.8 should do the job. If not i'm happy to fix it on site :-)

**Comment by ochorocho** [comment]
Closed due to no response. Reopen if this problem still exists
