### ISSUE TITLE
Detect path to typo3cms

### ISSUE THREAD

**Issue by koehnlein** [ochorocho/joro-typo3reversedeployment#26]
At the moment, the typo3cms binary is only searched in `../vendor/bin`. The deployment tool should support non-composer-based installations and automatically detect, if the binary is installed in composer mode or non-composer mode.

**Comment by ochorocho** [comment]
A simple approach to set typo3cms path:
https://github.com/ochorocho/joro-typo3reversedeployment/pull/27/files

**Comment by koehnlein** [comment]
#27

**Comment by ochorocho** [comment]
Feel free to reopen this if you think this is really needed. The current solution seems sufficient to me.
Thanks
