### ISSUE TITLE
Use ddev if installed

### ISSUE THREAD

**Issue by ochorocho** [ochorocho/joro-typo3reversedeployment#35]
It would be nice if ddev is used in the to do some nice stuff.
E.g. auto-import downloaded mysql-dump

**Comment by chriwo** [comment]
Currently I work on a change to use this package in a ddev container. So I switch to Symphony for the ssh authentication. Also the file sync must be change, thats a problem with access to the PHP temp folder in ddev container.

Are you interested in working together?

**Comment by ochorocho** [comment]
Hey, i have to get other stuff done first. But definitely interested :-)

**Comment by schliesser** [comment]
@chriwo did you get an error like this inside your ddev container?
```
rsync: failed to open files-from file /tmp.rsync_files: No such file or directory
rsync error: syntax or usage error (code 1) at main.c(1596) [client=3.1.3]
```

This should be fixed with #38

**Comment by chriwo** [comment]
Yes, I have the error and could it not fix. So, I'm back to simple batch scripts.

**Comment by schliesser** [comment]
Does it work if you change the line like in my PR?

**Comment by schliesser** [comment]
@chriwo  any update on this since #38 is merged?

**Comment by ochorocho** [comment]
Closing this due to no feedback.
But this package should work in ddev.
