### ISSUE TITLE
SSH-Key with passphrase

### ISSUE THREAD

**Issue by koehnlein** [ochorocho/joro-typo3reversedeployment#4]
I followed your example in your readme. But all I see, is "Login Failed" :-(

**Comment by koehnlein** [comment]
The problem is my passphrase protected private key.
I was able to create an unencrypted/unpretected copy of the key, using this command:

```
openssl rsa -in <Encrypted key filename>  -out < desired output file name>
```

**Comment by koehnlein** [comment]
Idea to solve this:

* new method `$reverseDeploy->setPrivateKeyPassphrase()`
* when passphrase is set, use phpseclib's `$ssh->setPassword()`
* Use environment variable and `getenv()` to set the password without adding it to the PHP code

**Comment by ochorocho** [comment]
Looks good to me. 👍 just go for it! ;-)

**Comment by ochorocho** [comment]
Tested and works for me 👍
