### ISSUE TITLE
More configuration options for downloading files

### ISSUE THREAD

**Issue by koehnlein** [ochorocho/joro-typo3reversedeployment#5]
It would be great to have more configuration options for downloading the files

* download all files, ingnoring `sys_file_reference`
* exclude folders (e.g. `fileadmin/_processed_`)
* download additional folders with different names (e.g. `/uploads`)

**Comment by ochorocho** [comment]
Thanks, will implement this hopefully soon-ish ...

**Comment by ochorocho** [comment]
Added following options
* $include - include specific folders
* $exclude - exclude files and folders
* $fileadminUsedOnly - Download only used files

let me know if this works for you. Thanks

**Comment by ochorocho** [comment]
Works at least for me :-)
