### ISSUE TITLE
Add variable for php cli path

### ISSUE THREAD

**Issue by schliesser** [ochorocho/joro-typo3reversedeployment#8]
https://github.com/ochorocho/joro-typo3reversedeployment/blob/faa8b0df40a1e8cf3d2330ffd0c5bb05dbd5add2/JoRo/Typo3ReverseDeployment.php#L342

On some servers we need to add the path to the php cli executable for `typo3cms` calls:

> X-Powered-By: PHP/4.4.9
> Content-type: text/html
> 
> This version of TYPO3 Console requires PHP 7.0.0 or above!
> Your PHP version is: 4.4.9
> Please specify a suitable PHP cli binary before the typo3cms binary like that:
> /path/to/php70-latest ../vendor/bin/typo3cms

**Comment by ochorocho** [comment]
closed in favor of #10
