### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by schliesser** [ochorocho/joro-typo3reversedeployment#9]
1. Use correct calls:
```
$reverseDeploy->setFileTarget("./fileadmin/");
$reverseDeploy->getFiles($ssh);
```

2. Use more generic example data for username and host

3. You can use exact file name `./folder/dump.sql` in setSqlTarget function or you use a folder `./dump/`, wich results in generic file names like `2018031336-db722877585.sql`

**Comment by ochorocho** [comment]
Would be nice to have docs rendered based on comments using doxygen

see http://doxygen.org

**Comment by ochorocho** [comment]
Readme updated.
doxygen added to generate Documentation
